name: todoo_app
description: "A simple todo app built using Flutter and Dart"

publish_to: 'none'


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconify_flutter: ^0.0.7
  flutter_riverpod: ^2.6.1
  salomon_bottom_bar: ^3.3.2
  uuid: ^4.5.1
  intl: ^0.20.1
  swipe_to: ^1.0.6
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  timezone: ^0.10.0
  app_settings: ^5.1.1
  flutter_svg: ^2.0.16
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Italic.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
  assets:
    - assets/illustrations/
